### ISSUE TITLE
fails to compile on newer netty releases due to StringUtil#split being removed

### ISSUE THREAD

**Issue by clenart** [sinetja/netty-router#16]
netty removed StringUtil#split in a subsequent release: https://github.com/netty/netty/commit/a80ea46b8e6d3b225547ae138a357101b0381268

since netty isn't shaded in `netty-router`, it's not possible to use `netty-router` with new releases of netty.

if you try, you receive this runtime error:

```
java.lang.NoSuchMethodError: io.netty.util.internal.StringUtil.split(Ljava/lang/String;C)[Ljava/lang/String;

    at io.netty.handler.codec.http.router.Path.<init>(Path.java:72)
    at io.netty.handler.codec.http.router.OrderlessRouter.addRoute(OrderlessRouter.java:58)
    at io.netty.handler.codec.http.router.MethodlessRouter.addRoute(MethodlessRouter.java:77)
    at io.netty.handler.codec.http.router.Router.addRoute(Router.java:193)
    at io.netty.handler.codec.http.router.Router.GET(Router.java:479)
```

**Comment by clenart** [comment]
one possible fix: https://github.com/sinetja/netty-router/pull/15

could also shade netty, or update the netty dependency.

**Comment by chigix** [comment]
The related pull request has been merged.
